//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SudCompany
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class СудоходнаяКомпанияEntities : DbContext
    {
        private static СудоходнаяКомпанияEntities _context;
        public СудоходнаяКомпанияEntities()
            : base("name=СудоходнаяКомпанияEntities")
        {
        }

        public static СудоходнаяКомпанияEntities GetContext()
        {
            if (_context == null)
            {
                _context = new СудоходнаяКомпанияEntities();
            }

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Администратор> Администратор { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Рейс> Рейс { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
        public virtual DbSet<Судно> Судно { get; set; }
    }
}
