//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SudCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рейс
    {
        public int Код { get; set; }
        public int КодСудна { get; set; }
        public int КодАдминистратора { get; set; }
        public int КодКлиента { get; set; }
        public int КодСтатуса { get; set; }
        public System.DateTime ДатаОтправления { get; set; }
        public Nullable<System.DateTime> ДатаПрибытия { get; set; }
        public string ГородОтправления { get; set; }
        public string ГородПрибытия { get; set; }
        public string Груз { get; set; }
        public string КапитанСудна { get; set; }
    
        public virtual Администратор Администратор { get; set; }
        public virtual Клиент Клиент { get; set; }
        public virtual Статус Статус { get; set; }
        public virtual Судно Судно { get; set; }
    }
}
